# Generated by Django 6.0.3 on 2026-05-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='cms/banners/')),
                ('redirect_url', models.CharField(blank=True, help_text='e.g. /shop?category=2', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Lowest number shows first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='Al Wholesale', max_length=255)),
                ('support_email', models.EmailField(default='support@alwholesale.ae', max_length=254)),
                ('support_phone', models.CharField(default='+971 00 000 0000', max_length=20)),
                ('default_vat_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
