# Generated by Django 6.0.3 on 2026-05-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='marquee_text',
            field=models.CharField(blank=True, help_text='Scrolling text for top banner', max_length=500, null=True),
        ),
    ]
