# Generated by Django 6.0.3 on 2026-05-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_sitesetting_marquee_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagebanner',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
