# Generated by Django 6.0.3 on 2026-05-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_business_name_user_is_approved_user_tax_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='United Arab Emirates', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vat_license_file',
            field=models.FileField(blank=True, null=True, upload_to='vendor_docs/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tax_info',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='VAT Number'),
        ),
    ]
