# Generated by Django 6.0.3 on 2026-04-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_order_alter_orderitem_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='buyer',
            new_name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Bank Transfer', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='price at the time of cart', max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
